### ISSUE TITLE
MNELAB

### ISSUE THREAD

**Issue by cbrnr** [fcbg-hnp/eeg-ICAtoolbox#6]
I saw that you created two dialog windows for MNE's t/f and ICA functionality. I am developing a GUI for MNE called MNELAB, which will include the most common functions for EEG analysis (similar in spirit to EEGLAB): https://github.com/cbrnr/mnelab
MNELAB already has PSD and ICA dialogs (although with fewer options than your app at the moment), and t/f support is planned to be added soon. Maybe you might want to give it a try and let me know what you think.

**Comment by tywr** [comment]
Hi,

First, thank you for taking time to reach us. We tried your gui, and it
seems quite close to what we would aim to do in the future. We are just at
the beginning of the project, so we think it would be interesting to
develop our tools alongside your framework in mnelab.

Maybe we can organize a skype meeting with us to discuss these topics a
little further.
